# Generated by Django 5.2.4 on 2025-07-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_project'),
        ('projectapp', '0002_project_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='projectapp.project'),
        ),
    ]
